apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: homelab-k3s
  namespace: flux-system
spec:
  interval: 10m
  path: ./flux/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: homelab
    namespace: flux-system
  components:
    - ./flux/secrets/k3s  
  dependsOn:
    - name: flux-system
  timeout: 2m
  wait: true
 Future encrypted secrets
